---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pj-recrutement-et-conseil
spec:
  selector:
    matchLabels:
      app: pj-recrutement-et-conseil
  template:
    metadata:
      labels:
        app: pj-recrutement-et-conseil
    spec:
      containers:
        - name: pj-recrutement-et-conseil
          image: shokohsc/pj-recrutement-et-conseil
          env:
            - name: ENV
              value: production
            - name: USE_SENTRY
              value: "false"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              port: http
              path: /
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 100m
              memory: 64M
