---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pj-formations
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    dashboard.shokohsc.home/name: dev-pj-formations
    dashboard.shokohsc.home/url: https://dev.pj-formations.shokohsc.home
    dashboard.shokohsc.home/icon: wrench
spec:
  rules:
  - host: dev.pj-formations.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pj-formations
            port:
              number: 80
  tls:
  - hosts:
    - dev.pj-formations.shokohsc.home
    secretName: pj-formations-cert
