apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-pj-recrutement-et-conseil
resources:
  - browser-sync/
bases:
  - ../../base
patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
