apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-pj-formations
resources:
  - browser-sync/
bases:
  - ../../base
patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
